site_name: Редактура
site_url: https://example.com/
nav:
    - Home: index.md
    - Статьи: 
        - articles/Полезное.md
        - articles/1.md
        - articles/2.md
        - articles/3.md
        - articles/4.md
        - articles/5.md
    #- Документы: 
    #    - documents/
    - Ссылки: links.md
    - About: about.md
theme:
    name: material
    #custom_dir: overrides
    font: false
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Темное оформление
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Светлое оформление
    features:
      - navigation.indexes
      - navigation.expand
plugins:
  - search
  - i18n:
      #docs_structure: suffix
      default_language: ru
      languages:
        ru:
          name: Russian
          build: true
          site_name: "Редактура"
markdown_extensions:
  - def_list
  - pymdownx.magiclink # auto-link HTML, FTP, and email links https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.keys # add keys like ++ctrl+alt+delete++ # https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.tabbed # add tabs https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.details # add spoiler (??? note) https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.snippets # insert a file into another markdown file https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.superfences # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - footnotes # https://python-markdown.github.io/extensions/footnotes/
  - tables # https://python-markdown.github.io/extensions/tables/
  - admonition # tips & notes (!!! note) https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - attr_list # https://python-markdown.github.io/extensions/attr_list/
  - smarty # converts ASCII dashes, quotes and ellipses to their HTML entity equivalents https://python-markdown.github.io/extensions/smarty/